export const scores = [{
    physics:[
        {
            studentName:"Sam",
            indexNo:1000,
            score:50
        },{
            studentName:"Alex",
            indexNo:1001,
            score:67
        },
        {
            studentName:"John",
            indexNo:1002,
            score:34
        },
        {
            studentName:"Tina",
            indexNo:1003,
            score:27
        },
        {
            studentName:"Jake",
            indexNo:1004,
            score:78
        },
        {
            studentName:"Sansa",
            indexNo:1005,
            score:98
        },
        {
            studentName:"Fred",
            indexNo:1006,
            score:45
        },
        {
            studentName:"Olly",
            indexNo:1007,
            score:99
        },
        {
            studentName:"Sill",
            indexNo:1008,
            score:34
        },
        {
            studentName:"Nave",
            indexNo:1009,
            score:81
        }
    ],
    maths:[
        {
            studentName:"Sam",
            indexNo:1000,
            score:60
        },{
            studentName:"Alex",
            indexNo:1001,
            score:67
        },
        {
            studentName:"John",
            indexNo:1002,
            score:34
        },
        {
            studentName:"Tina",
            indexNo:1003,
            score:27
        },
        {
            studentName:"Jake",
            indexNo:1004,
            score:99
        },
        {
            studentName:"Sansa",
            indexNo:1005,
            score:98
        },
        {
            studentName:"Fred",
            indexNo:1006,
            score:45
        },
        {
            studentName:"Olly",
            indexNo:1007,
            score:23
        },
        {
            studentName:"Sill",
            indexNo:1008,
            score:34
        },
        {
            studentName:"Nave",
            indexNo:1009,
            score:81
        }
    ],
    chemistry:[
        {
            studentName:"Sam",
            indexNo:1000,
            score:70
        },{
            studentName:"Alex",
            indexNo:1001,
            score:67
        },
        {
            studentName:"John",
            indexNo:1002,
            score:34
        },
        {
            studentName:"Tina",
            indexNo:1003,
            score:27
        },
        {
            studentName:"Jake",
            indexNo:1004,
            score:78
        },
        {
            studentName:"Sansa",
            indexNo:1005,
            score:90
        },
        {
            studentName:"Fred",
            indexNo:1006,
            score:45
        },
        {
            studentName:"Olly",
            indexNo:1007,
            score:23
        },
        {
            studentName:"Sill",
            indexNo:1008,
            score:99
        },
        {
            studentName:"Nave",
            indexNo:1009,
            score:81
        }
    ]

}];






export const Physics = [
    {
        studentName:"Sam",
        indexNo:1000,
        score:56
    },{
        studentName:"Alex",
        indexNo:1001,
        score:67
    },
    {
        studentName:"John",
        indexNo:1002,
        score:34
    },
    {
        studentName:"Tina",
        indexNo:1003,
        score:27
    },
    {
        studentName:"Jake",
        indexNo:1004,
        score:78
    },
    {
        studentName:"Sansa",
        indexNo:1005,
        score:98
    },
    {
        studentName:"Fred",
        indexNo:1006,
        score:45
    },
    {
        studentName:"Olly",
        indexNo:1007,
        score:23
    },
    {
        studentName:"Sill",
        indexNo:1008,
        score:34
    },
    {
        studentName:"Nave",
        indexNo:1009,
        score:81
    }
];


export const Maths = [
    {
        studentName:"Sam",
        indexNo:1000,
        score:56
    },{
        studentName:"Alex",
        indexNo:1001,
        score:67
    },
    {
        studentName:"John",
        indexNo:1002,
        score:34
    },
    {
        studentName:"Tina",
        indexNo:1003,
        score:27
    },
    {
        studentName:"Jake",
        indexNo:1004,
        score:78
    },
    {
        studentName:"Sansa",
        indexNo:1005,
        score:98
    },
    {
        studentName:"Fred",
        indexNo:1006,
        score:45
    },
    {
        studentName:"Olly",
        indexNo:1007,
        score:23
    },
    {
        studentName:"Sill",
        indexNo:1008,
        score:34
    },
    {
        studentName:"Nave",
        indexNo:1009,
        score:81
    }
];



export const chemistry = [
    {
        studentName:"Sam",
        indexNo:1000,
        score:56
    },{
        studentName:"Alex",
        indexNo:1001,
        score:67
    },
    {
        studentName:"John",
        indexNo:1002,
        score:34
    },
    {
        studentName:"Tina",
        indexNo:1003,
        score:27
    },
    {
        studentName:"Jake",
        indexNo:1004,
        score:78
    },
    {
        studentName:"Sansa",
        indexNo:1005,
        score:98
    },
    {
        studentName:"Fred",
        indexNo:1006,
        score:45
    },
    {
        studentName:"Olly",
        indexNo:1007,
        score:23
    },
    {
        studentName:"Sill",
        indexNo:1008,
        score:34
    },
    {
        studentName:"Nave",
        indexNo:1009,
        score:81
    }
];